import type { LiveAstroContext, NatalLensResult } from "../astrology/astroTypes";
import type { LocalSynthesis, ReadingPacket, SymbolEntry } from "./readingPacket";

function describeSymbols(symbols: SymbolEntry[]): string {
  if (!symbols.length) {
    return "No tarot or rune symbols are available yet because the source JSON has not been wired.";
  }

  return symbols
    .map((symbol) => `${symbol.position ? `${symbol.position}: ` : ""}${symbol.name}${symbol.reversed ? " reversed" : ""}`)
    .join("; ");
}

function describeAstrology(context?: LiveAstroContext): string {
  if (!context || context.status !== "available") {
    return "Live astrology is scaffolded but not connected.";
  }

  return [
    context.sunSign && `Sun in ${context.sunSign}`,
    context.moonSign && `Moon in ${context.moonSign}`,
    context.moonPhase && `${context.moonPhase} Moon`,
    context.dominantElement && `${context.dominantElement} emphasis`
  ]
    .filter(Boolean)
    .join(", ");
}

function describeNatalLens(lens?: NatalLensResult): string {
  if (!lens || lens.status !== "available") {
    return "Natal/profile routing is scaffolded but not connected.";
  }

  return lens.routes.map((route) => route.label).join(", ");
}

export function buildLocalSynthesis(packet: ReadingPacket): LocalSynthesis {
  const symbolLine = describeSymbols(packet.symbols);
  const astroLine = describeAstrology(packet.liveAstrology);
  const natalLine = describeNatalLens(packet.natalLens);
  const hasSymbols = packet.symbols.length > 0;

  return {
    title: hasSymbols ? "Local Synthesis" : "Integration Awaiting Source Data",
    summary: hasSymbols
      ? `${symbolLine}. ${astroLine}. ${natalLine}.`
      : "The ritual console is running, but the reading engine is intentionally waiting for your existing tarot/rune/astrology data.",
    strands: [
      `Symbol layer: ${symbolLine}`,
      `Sky layer: ${astroLine}`,
      `Personal lens: ${natalLine}`
    ],
    practicalVersion: hasSymbols
      ? "Review the static meanings first, then treat any synthesis as a composed lens rather than a command."
      : "Drop in or wire the existing datasets, then regenerate the packet from the Tarot or Runes tab.",
    mythicVersion: hasSymbols
      ? "The console braids symbol, sky, and profile into a single chamber of attention."
      : "The chamber is built. The named spirits of the system have not been invited into the code yet.",
    sourceNotes: [
      "Local synthesis uses only fields present in the ReadingPacket.",
      "No tarot, rune, or astrology meanings are generated by this scaffold."
    ]
  };
}
